add helper for computing noise_multiplier from epsilon
tensorflow/privacy pull request #143
Opened 2020-11-20 02:28 UTC by jagielski

A common workflow starts from a privacy budget, and requires obtaining the noise multiplier that is required for DP-SGD to satisfy the given privacy budget. With the current codebase, this requires running a binary search. This pull request implements this binary search. It can be found in the analysis/compute_noise_from_budget.py script, using the same API as the existing analysis/compute_dp_sgd_privacy.py.

2020-12-22 00:55 UTC, schien1729 requested changes
Thanks, Matthew! This is indeed a useful tool that users have requested. I've made some minor suggestions-- sorry it took so long.

2020-12-22 00:55 UTC, schien1729 commented on tensorflow_privacy/privacy/analysis/compute_noise_from_budget.py
> +  compute_dp_sgd_privacy
Please update this command line to reflect name of program.

2020-12-22 00:55 UTC, schien1729 commented on tensorflow_privacy/privacy/analysis/compute_noise_from_budget_lib.py
> +    raise app.UsageError('n must be larger than the batch size.')
Minor note: Given that n is usually fixed, while the batch size can be varied, maybe rephrase this to say that batch size must be at most n?

2020-12-22 00:55 UTC, schien1729 commented on tensorflow_privacy/privacy/analysis/compute_noise_from_budget.py
> +def main(argv):
As I read it, in the rare case that noise of 1e-5 is too much, there's not much the user can do to use this tool. Can you either document that, or maybe add a minimum noise argument to compute_noise, defaulting to 1e-5?

2021-01-19 18:26 UTC, jagielski commented
Thanks for the comments, Steve! I've addressed each of your comments in the latest commit. On the last one, I've elected to add a min_noise parameter, and I've added a test to check that if min_noise is too large, it has the expected behavior (just return 0).

2021-02-22 23:12 UTC, schien1729 approved these changes

2021-02-23 00:01 UTC, merged